main: net.silverstonemc.silverstonecreative.SilverstoneCreative
name: SilverstoneCreative
description: Designed for the Creative server
version: %VERSION%
author: JasonHorkles
api-version: '1.21.11'
depend:
  - PlotSquared
