join-leave-spam:
  # After how long in seconds the leave count should expire
  expire-after: 25
  # After how many joins and leaves should the player be warned?
  leaves: 4
  # What should we warn them for?
  warn: "joinleavespam"
