# minigames, creative (#serverSpecific)
server: "minigames"

# Lore for the buy GUI
buy-gui:
  member:
    - "&2$5 USD"
    - "&7&oClick to purchase"
    - ""
    - "&3&nPerks"
    - "&3- &x&3&4&b&a&e&bMember suffix"
    - "&3- &x&3&4&b&a&e&bMake up to 4 Creative plots"
    - "&b  (up from 2)"
    - "&3- &x&3&4&b&a&e&b/nick command"
    - "&3- &x&3&4&b&a&e&b/hat command"
    - "&3- &x&3&4&b&a&e&b/joinleavesounds command"

  vip:
    - "&2$10 USD"
    - "&7&oClick to purchase"
    - ""
    - "&3&nPerks"
    - "&3- &x&3&4&b&a&e&bVIP suffix"
    - "&3- &x&3&4&b&a&e&bNickname colors"
    - "&3- &x&3&4&b&a&e&bMake up to 6 Creative plots"
    - "&3- &x&3&4&b&a&e&b/pp &b(player particles) &x&3&4&b&a&e&bcommand"
    - "&3- &x&3&4&b&a&e&b/chatsounds command"
    - "&3- &x&3&4&b&a&e&bAll Member perks"

  vip+:
    - "&2$20 USD"
    - "&7&oClick to purchase"
    - ""
    - "&3&nPerks"
    - "&3- &x&3&4&b&a&e&bVIP+ suffix"
    - "&3- &x&3&4&b&a&e&bJoin full server"
    - "&3- &x&3&4&b&a&e&bChat colors &b(default chat color"
    - "  &bis customizable with /chatcolor)"
    - "&3- &x&3&4&b&a&e&bMake up to 9 Creative plots"
    - "&3- &x&3&4&b&a&e&bAll Member and VIP perks"

  mvp:
    - "&2$30 USD"
    - "&7&oClick to purchase"
    - ""
    - "&3&nPerks"
    - "&3- &x&3&4&b&a&e&bMVP suffix"
    - "&3- &x&3&4&b&a&e&bBragging rights"
    - "&3- &x&3&4&b&a&e&bBe displayed in the Credits warp"
    - "&3- &x&3&4&b&a&e&bMake up to 16 Creative plots"
    - "&3- &x&3&4&b&a&e&bAll Member, VIP, and VIP+ perks"

  donate:
    - "&2$1 USD minimum"
    - "&7&oClick to purchase"
    - ""
    - "&x&3&4&b&a&e&bYou can donate any amount you'd like"
    - "&x&3&4&b&a&e&bwith a minimum of $1"
    - ""
    - "&x&3&4&b&a&e&bAll donations are greatly appreciated"
    - "&x&3&4&b&a&e&band help the server a ton"
