# minigames, creative, survival, events (#serverSpecific)
server: "minigames"

tips:
  1:
    header: "Toggles"
    tips:
      - "<b>/command</b> - Neat!"
      - "<b>/command2</b> - Neat2!"
      - "<b>/command3</b> - Neat3!"
  2:
    header: "Pain"
    tips:
      - "<b>/kill</b> - Kills"

# Lore for the buy GUI
buy-gui:
  member:
    - "<dark_green>$5 USD"
    - "<gray><i>Click to purchase"
    - ""
    - "<aqua><u>Perks"
    - "<dark_aqua>- <#34baeb>Member suffix"
    - "<dark_aqua>- <#34baeb>Make up to 4 Creative plots"
    - "<dark_aqua>  (up from 2)"
    - "<dark_aqua>- <#34baeb>/nick command"
    - "<dark_aqua>- <#34baeb>/hat command"
    - "<dark_aqua>- <#34baeb>/joinleavesounds command"

  vip:
    - "<dark_green>$10 USD"
    - "<gray><i>Click to purchase"
    - ""
    - "<aqua><u>Perks"
    - "<dark_aqua>- <#34baeb>VIP suffix"
    - "<dark_aqua>- <#34baeb>Nickname colors"
    - "<dark_aqua>- <#34baeb>Make up to 6 Creative plots"
    - "<dark_aqua>- <#34baeb>/pp <dark_aqua>(player particles) <#34baeb>command"
    - "<dark_aqua>- <#34baeb>/chatsounds command"
    - "<dark_aqua>- <#34baeb>/sit command anywhere"
    - "<#34baeb>  in the Creative server"
    - "<dark_aqua>- <#34baeb>All Member perks"

  vip+:
    - "<dark_green>$20 USD"
    - "<gray><i>Click to purchase"
    - ""
    - "<aqua><u>Perks"
    - "<dark_aqua>- <#34baeb>VIP+ suffix"
    - "<dark_aqua>- <#34baeb>Join full server"
    - "<dark_aqua>- <#34baeb>Chat colors <dark_aqua>(default chat color"
    - "<dark_aqua>  is customizable with /chatcolor)"
    - "<dark_aqua>- <#34baeb>Make up to 9 Creative plots"
    - "<dark_aqua>- <#34baeb>All Member and VIP perks"

  mvp:
    - "<dark_green>$30 USD"
    - "<gray><i>Click to purchase"
    - ""
    - "<aqua><u>Perks"
    - "<dark_aqua>- <#34baeb>MVP suffix"
    - "<dark_aqua>- <#34baeb>Bragging rights"
    - "<dark_aqua>- <#34baeb>Be displayed in the Credits warp"
    - "<dark_aqua>- <#34baeb>Make up to 16 Creative plots"
    - "<dark_aqua>- <#34baeb>All Member, VIP, and VIP+ perks"

  donate:
    - "<dark_green>$1 USD minimum"
    - "<gray><i>Click to purchase"
    - ""
    - "<#34baeb>You can donate any amount you'd like"
    - "<#34baeb>with a minimum of $1"
    - ""
    - "<#34baeb>All donations are greatly appreciated"
    - "<#34baeb>and help the server a ton"

discord-token: ""
heartbeat-url: ""
