# main, minigames, building (#serverSpecific)
server: "main"

# Lore for the buy GUI
buyGUI:
  Member:
    1:
      - "&2$10 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bMember suffix"
      - "&3- &x&3&4&b&a&e&b$25 every 30 minutes"
      - "&3- &x&3&4&b&a&e&b/nick command"
      - "&3- &x&3&4&b&a&e&b/ec &b(ender chest) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/wb &b(crafting table) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/hat command"
      - "&3- &x&3&4&b&a&e&b/compact command"
      - "&3- &x&3&4&b&a&e&b/music command"
      - "&3- &x&3&4&b&a&e&b/joinleavesounds command"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&2$10 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nMore Perks"
      - "&3- &x&3&4&b&a&e&bMax home limit increased"
      - "&x&3&4&b&a&e&b  from 10 to 15"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased"
      - "&x&3&4&b&a&e&b  from 5 to 7"
      - "&3- &x&3&4&b&a&e&bMax flight time increased"
      - "&x&3&4&b&a&e&b  from 1 hour to 2 hours"
      - ""
      - "&8«  &7Page 2/2"
  VIP:
    1:
      - "&2$20 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bVIP suffix"
      - "&3- &x&3&4&b&a&e&b$50 every 30 minutes"
      - "&3- &x&3&4&b&a&e&bNickname colors"
      - "&3- &x&3&4&b&a&e&b/top command &b(only in the"
      - "  &bOverworld and the End)"
      - "&3- &x&3&4&b&a&e&b/pp &b(player particles) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/chatsounds command"
      - "&3- &x&3&4&b&a&e&b/sit command &b(sit on any block"
      - "  &bbesides just stairs, slabs, and carpet)"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&2$20 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nMore Perks"
      - "&3- &x&3&4&b&a&e&bMax home limit increased to 25"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 10"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 3 hours"
      - "&3- &x&3&4&b&a&e&bAll Member perks as well"
      - ""
      - "&8«  &7Page 2/2"
  VIP+:
    1:
      - "&2$30 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bVIP+ suffix"
      - "&3- &x&3&4&b&a&e&b$75 every 30 minutes"
      - "&3- &x&3&4&b&a&e&bJoin full server"
      - "&3- &x&3&4&b&a&e&bNo teleport delay"
      - "&3- &x&3&4&b&a&e&bChat colors &b(default chat color"
      - "  &bis customizable with /chatcolor)"
      - "&3- &x&3&4&b&a&e&b/chestsort command"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&2$30 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nMore Perks"
      - "&3- &x&3&4&b&a&e&bMax home limit increased to 50"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 15"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 4 hours"
      - "&3- &x&3&4&b&a&e&bAll Member and VIP perks as well"
      - ""
      - "&8«  &7Page 2/2"
  MVP:
    1:
      - "&2$50 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bMVP suffix"
      - "&3- &x&3&4&b&a&e&b$100 every 30 minutes"
      - "&3- &x&3&4&b&a&e&bBe displayed in the Credits warp"
      - "&3- &x&3&4&b&a&e&bFly in the Nether &b(/fly to toggle)"
      - "&3- &x&3&4&b&a&e&b/heal command &b(only in the"
      - "  &bOverworld and the Nether | $500 per use)"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&2$50 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nMore Perks"
      - "&3- &x&3&4&b&a&e&bMax home limit increased to 100"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 25"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 5 hours"
      - "&3- &x&3&4&b&a&e&bAll Member, VIP, and VIP+ perks as well"
      - ""
      - "&8«  &7Page 2/2"
  Donate:
    1:
      - "&2$1 USD minimum"
      - "&7&oClick to purchase"
      - ""
      - "&x&3&4&b&a&e&bYou can donate any amount you'd like"
      - "&x&3&4&b&a&e&bwith a minimum of $1."
      - "&x&3&4&b&a&e&bYour donations are extremely appreciated"
      - "&x&3&4&b&a&e&band help the server greatly."
      - "&x&3&4&b&a&e&bYou may also choose to"
      - "&x&3&4&b&a&e&bdonate monthly if you wish."

socialGUI:
  Discord:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19"
    message: "&6Partnered Discord server: &bdiscord.gg/dXJPpnt &3(Minecraft Building)\n&a&lOfficial Discord server: &bdiscord.gg/VVSUEPd &3(News, polls, and more)"
  GitHub:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZlMjdkYTEyODE5YThiMDUzZGEwY2MyYjYyZGVjNGNkYTkxZGU2ZWVlYzIxY2NmM2JmZTZkZDhkNDQzNmE3In19fQ=="
    message: "&fFollow JasonHorkles on GitHub @ &bgithub.com/JasonHorkles"
  Instagram:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM4OGQ2MTYzZmFiZTdjNWU2MjQ1MGViMzdhMDc0ZTJlMmM4ODYxMWM5OTg1MzZkYmQ4NDI5ZmFhMDgxOTQ1MyJ9fX0="
    message: "&x&E&1&3&0&6&CFollow JasonHorkles on Instagram @ &binstagram.com/jason.horkles_photo &x&E&1&3&0&6&C& &binstagram.com/jason.horkles_renders"
  Twitch:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiZTY1ZjQ0Y2QyMTAxNGM4Y2RkZDAxNThiZjc1MjI3YWRjYjFmZDE3OWY0YzFhY2QxNThjODg4NzFhMTNmIn19fQ=="
    message: "&x&6&4&4&1&a&5Follow JasonHorkles on Twitch @ &btwitch.tv/jasonhorkles"
  Twitter:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY4NWEwYmU3NDNlOTA2N2RlOTVjZDhjNmQxYmEyMWFiMjFkMzczNzFiM2Q1OTcyMTFiYjc1ZTQzMjc5In19fQ=="
    message: "&x&1&D&A&1&F&2Follow JasonHorkles on Twitter @ &btwitter.com/JasonHorkles"
  YouTube:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA0MmM3YmMyZGI4NTM0N2U2YTM2OTI4ZTlhMTQ2YjRmYzNlMWRlZjRmZWJmMjc5MzkxYmUxNWRlN2Y0NmUifX19"
    message: "&x&f&2&1&8&2&fFollow JasonHorkles on YouTube @ &byoutube.com/JasonHorkles"
