# main, creative, minigames, building (#serverSpecific)
server: "main"

# Lore for the buy GUI
buyGUI:
  Member:
    1:
      - "&2$5 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bExtra homes &b(now 15 available)"
      - "&3- &x&3&4&b&a&e&bMember suffix"
      - "&3- &x&3&4&b&a&e&b/nick command"
      - "&3- &x&3&4&b&a&e&b/ec &b(ender chest) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/wb &b(crafting table) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/hat command"
      - "&3- &x&3&4&b&a&e&b/compact command"
      - "&3- &x&3&4&b&a&e&b/music command"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&b/joinleavesounds command"
      - "&3- &x&3&4&b&a&e&b100 claim blocks per hour"
      - "&b  (upgrade from 75)"
      - "&3- &x&3&4&b&a&e&b$25 every 30 minutes"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased "
      - "&x&3&4&b&a&e&b  from 5 to 10"
      - "&3- &x&3&4&b&a&e&bMax flight time increased"
      - "&x&3&4&b&a&e&b  from 1 hour to 2 hours"
      - ""
      - "&8«  &7Page 2/2"
  VIP:
    1:
      - "&2$10 USD"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bExtra homes &b(now 25 available)"
      - "&3- &x&3&4&b&a&e&bVIP suffix"
      - "&3- &x&3&4&b&a&e&b/top command &b(survival worlds only)"
      - "&3- &x&3&4&b&a&e&bNickname colors"
      - "&3- &x&3&4&b&a&e&b/pp &b(player particles) &x&3&4&b&a&e&bcommand"
      - "&3- &x&3&4&b&a&e&b/chatsounds command"
      - "&3- &x&3&4&b&a&e&b$50 every 30 minutes"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&b150 claim blocks per hour"
      - "  &b(upgrade from 75)"
      - "&3- &x&3&4&b&a&e&b/sit command &b(sit on any block"
      - "  &bbesides just stairs, slabs, and carpet)"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 15"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 3 hours"
      - "&3- &x&3&4&b&a&e&bAll Member perks as well"
      - ""
      - "&8«  &7Page 2/2"
  VIP+:
    1:
      - "&2$15 USD/month"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bExtra homes &b(now 50 available)"
      - "&3- &x&3&4&b&a&e&bVIP+ suffix"
      - "&3- &x&3&4&b&a&e&bChat colors &b(default chat color"
      - "  &bis customizable with /chatcolor)"
      - "&3- &x&3&4&b&a&e&bUnlimited fly in survival Overworld"
      - "  &b(/fly to toggle)"
      - "&3- &x&3&4&b&a&e&bJoin full server"
      - "&3- &x&3&4&b&a&e&bNo teleport delay"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&b/chestsort command"
      - "&3- &x&3&4&b&a&e&b$100 every 30 minutes"
      - "&3- &x&3&4&b&a&e&b200 claim blocks per hour"
      - "  &b(upgrade from 75, 100,"
      - "  &bor 150 depending on rank)"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 20"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 4 hours"
      - "&3- &x&3&4&b&a&e&bAll Member and VIP perks as well"
      - ""
      - "&8«  &7Page 2/2"
  MVP:
    1:
      - "&2$20 USD/month"
      - "&7&oLeft click to purchase"
      - "&7&oRight click to change page"
      - ""
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bExtra homes &b(now 100 available)"
      - "&3- &x&3&4&b&a&e&bMVP suffix"
      - "&3- &x&3&4&b&a&e&bFly in survival Nether &b(/fly to toggle)"
      - "&3- &x&3&4&b&a&e&b/heal command &b(only in survival"
      - "  &bOverworld and Nether | $500 per use)"
      - "&3- &x&3&4&b&a&e&bDisplayed in Credits warp"
      - "&3- &x&3&4&b&a&e&bAFK kick bypass &b(survival worlds only)"
      - ""
      - "    &7Page 1/2  &8»"
    2:
      - "&3&nPerks"
      - "&3- &x&3&4&b&a&e&bCompletely support the server"
      - "&3- &x&3&4&b&a&e&bMax RTP limit increased to 30"
      - "&3- &x&3&4&b&a&e&bMax flight time increased to 5 hours"
      - "&3- &x&3&4&b&a&e&bAll Member, VIP, and VIP+ perks as well"
      - ""
      - "&8«  &7Page 2/2"
  Donate:
    1:
      - "&2$1 USD minimum"
      - "&7&oClick to purchase"
      - ""
      - "&x&3&4&b&a&e&bYou can donate any amount you'd like,"
      - "&x&3&4&b&a&e&bwith a minimum of $1."
      - "&x&3&4&b&a&e&bYour donations are greatly appreciated"
      - "&x&3&4&b&a&e&band help the server a ton."
      - "&x&3&4&b&a&e&bYou may also choose to"
      - "&x&3&4&b&a&e&bdonate monthly if you'd like."

socialGUI:
  Discord:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19"
    message: "&6Partnered Discord server: &bdiscord.gg/dXJPpnt &3(Minecraft Building)\n&a&lOfficial Discord server: &bdiscord.gg/VVSUEPd &3(News, polls, and more)"
  GitHub:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZlMjdkYTEyODE5YThiMDUzZGEwY2MyYjYyZGVjNGNkYTkxZGU2ZWVlYzIxY2NmM2JmZTZkZDhkNDQzNmE3In19fQ=="
    message: "&fFollow JasonHorkles on GitHub @ &bgithub.com/JasonHorkles"
  Instagram:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM4OGQ2MTYzZmFiZTdjNWU2MjQ1MGViMzdhMDc0ZTJlMmM4ODYxMWM5OTg1MzZkYmQ4NDI5ZmFhMDgxOTQ1MyJ9fX0="
    message: "&x&E&1&3&0&6&CFollow JasonHorkles on Instagram @ &binstagram.com/jason.horkles_photo &x&E&1&3&0&6&C& &binstagram.com/jason.horkles_renders"
  Twitch:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiZTY1ZjQ0Y2QyMTAxNGM4Y2RkZDAxNThiZjc1MjI3YWRjYjFmZDE3OWY0YzFhY2QxNThjODg4NzFhMTNmIn19fQ=="
    message: "&x&6&4&4&1&a&5Follow JasonHorkles on Twitch @ &btwitch.tv/jasonhorkles"
  Twitter:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY4NWEwYmU3NDNlOTA2N2RlOTVjZDhjNmQxYmEyMWFiMjFkMzczNzFiM2Q1OTcyMTFiYjc1ZTQzMjc5In19fQ=="
    message: "&x&1&D&A&1&F&2Follow JasonHorkles on Twitter @ &btwitter.com/JasonHorkles"
  YouTube:
    skullID: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA0MmM3YmMyZGI4NTM0N2U2YTM2OTI4ZTlhMTQ2YjRmYzNlMWRlZjRmZWJmMjc5MzkxYmUxNWRlN2Y0NmUifX19"
    message: "&x&f&2&1&8&2&fFollow JasonHorkles on YouTube @ &byoutube.com/JasonHorkles"

# The rules for the server
rules:
  # The text to add before the rule number when sending a player a rule
  rule-prefix: "<dark_green>{#} <gray>| <#23B8CF>"
  number-of-rules: 11
  header:
    - ""
    - "<dark_aqua> ---------- <green>Rules <dark_aqua>----------"
    - ""
  1: "No swearing and don't try to bypass the swear filter"
  2: "Hacked and <#15E8E8><click:open_url:https://github.com/SilverstoneMC/Silverstone/wiki/Modifications><underlined>other modified clients</underlined>*</click> <#23B8CF>are prohibited"
  3: "No griefing / exploits / cheating <dark_aqua>(includes x-ray resource packs | breaking bedrock in Nether is allowed)"
  4: "Don't spam <dark_aqua>(neither caps nor characters)"
  5: "Be kind and use common sense"
  6: "No anti-AFK methods"
  7: "No advertising"
  8: "Respect all players & staff"
  9: "Only talk in English <dark_aqua>(use &7/tell <player> &3to speak another language)"
  10: "Don't impersonate others"
  11: "Don't build within 250 blocks of someone else without their permission"
  footer:
    - ""
    - "<dark_aqua>Type <green>/tips <dark_aqua>to get a list of all tips for the server!"
  # The rules to show in the GUI menu
  GUI:
    1:
      - "&x&2&3&b&8&c&fNo swearing and don't"
      - "&x&2&3&b&8&c&ftry to bypass the swear filter"
    2:
      - "&x&2&3&b&8&c&fHacked and other modified"
      - "&x&2&3&b&8&c&fclients are not allowed"
    3:
      - "&x&2&3&b&8&c&fNo griefing / exploits / cheating"
      - "&3(includes x-ray resource packs | "
      - "&3breaking bedrock in Nether is allowed)"
    4:
      - "&x&2&3&b&8&c&fDon't spam &3(neither caps"
      - "&3nor characters)"
    5:
      - "&x&2&3&b&8&c&fBe kind and appropriate"
    6:
      - "&x&2&3&b&8&c&fNo anti-AFK methods"
    7:
      - "&x&2&3&b&8&c&fNo advertising"
    8:
      - "&x&2&3&b&8&c&fRespect all players & staff"
    9:
      - "&x&2&3&b&8&c&fOnly talk in English"
      - "&3(use &7/tell <player> &3to"
      - "&3speak another language)"
    10:
      - "&x&2&3&b&8&c&fDon't impersonate others"
    11:
      - "&x&2&3&b&8&c&fDon't build within 300 blocks"
      - "&x&2&3&b&8&c&fof someone else without"
      - "&x&2&3&b&8&c&ftheir permission"
