main: net.silverstonemc.silverstoneglobal.SilverstoneGlobal
name: SilverstoneGlobal
description: Designed for the Silverstone network backend servers
version: %VERSION%
author: JasonHorkles
api-version: 1.19
softdepend:
  - DiscordSRV
  - Matrix
  - Essentials
  - ViaVersion
depend:
  - LuckPerms

commands:
  bclag:
    permission: silverstone.admin
  bcnolag:
    permission: silverstone.admin
  bcrestart:
    permission: silverstone.admin
  bcshutdown:
    permission: silverstone.admin
  buy:
    aliases: [ ranks, donate ]
  chatcolor:
    permission: silverstone.chatcolor
  chatsounds:
    permission: silverstone.chatsounds
  discord:
    aliases: [ news ]
  effects:
    permission: silverstone.moderator
  exit:
    description: "Exit the server"
    permission: silverstone.exit
  facepalm:
    description: "Facepalm emote"
  forcerestart:
    permission: silverstone.admin
  freezeserver:
    permission: silverstone.owner
    usage: "§cUsage: /freezeserver <seconds> confirm"
  joinleavesounds:
    permission: silverstone.jlsounds
  listops:
    aliases: [ oplist ]
    permission: silverstone.admin
  live:
    permission: silverstone.owner
  localchat:
    aliases: [ lc, local ]
    permission: silverstone.admin
    usage: "§cUsage: /localchat <message>"
  monitortps:
    aliases: [ tpsmonitor ]
    permission: silverstone.admin
    usage: "Usage: /monitortps [interval]"
  nv:
    aliases: [ nightvision ]
    permission: silverstone.nightvision
  quickrestart:
    permission: silverstone.admin
  restart:
    aliases: [ cancelrestart ]
    permission: silverstone.admin
  restartwhenempty:
    permission: silverstone.admin
  schedulerestart:
    permission: silverstone.admin
  shrug:
    description: "Shrug emote"
  silverstoneglobal:
    aliases: [ ssg ]
    permission: silverstone.admin
    usage: "Usage: /ssg reload"
  spectate:
    aliases: [ spec ]
    permission: silverstone.moderator
    usage: "§cUsage: /spectate <player>"
  tableflip:
    description: "Tableflip emote"
  tpchunk:
    permission: silverstone.admin
    usage: "§cUsage: /tpchunk <x> <z> [world]"
  tpregion:
    permission: silverstone.admin
    usage: "§cUsage: /tpregion <x> <z> [world]"
  updatecommands:
    description: "Updates available commands"
  watch:
    permission: silverstone.moderator
    usage: "§cUsage: /watch <player>"

permissions:
  silverstone.admin:
    default: op
  silverstone.chatcolor:
    default: op
  silverstone.chatsounds.enabled:
    default: false
  silverstone.chatsounds:
    default: false
  silverstone.console:
    default: op
  silverstone.exit:
    default: true
  silverstone.jlsounds.enabled:
    default: false
  silverstone.jlsounds:
    default: op
  silverstone.live:
    default: false
  silverstone.moderator:
    default: op
  silverstone.nightvision:
    default: op
  silverstone.owner:
    default: op
