main: net.silverstonemc.silverstoneglobal.SilverstoneGlobal
name: SilverstoneGlobal
description: Designed for the Silverstone network
version: %VERSION%
author: JasonHorkles
api-version: 1.18
softdepend:
  - DiscordSRV
  - Matrix
  - Essentials
  - ViaVersion
depend:
  - LuckPerms

commands:
  bclag:
    permission: silverstone.admin
  bcnolag:
    permission: silverstone.admin
  bcrestart:
    permission: silverstone.admin
  bcshutdown:
    permission: silverstone.admin
  buy:
    aliases: [ ranks, donate ]
  chatcolor:
    permission: silverstone.chatcolor
  chatsounds:
    permission: silverstone.chatsounds
  discord:
    aliases: [ news ]
    description: "A social command"
  effects:
    permission: silverstone.trialmod
  exit:
    description: "Exit the server"
    permission: silverstone.exit
  facepalm:
    description: "Facepalm emote"
  firework:
    permission: silverstone.admin
  fixlight:
    aliases: [ recalculatelighting ]
    permission: silverstone.fixlight
  forcerestart:
    permission: silverstone.admin
  freezeserver:
    permission: silverstone.owner
    usage: "§cUsage: /freezeserver <seconds> confirm"
  github:
    description: "A social command"
  help:
    description: "Get help"
  instagram:
    description: "A social command"
  joinleavesounds:
    permission: silverstone.jlsounds
  listops:
    aliases: [ oplist ]
    permission: silverstone.admin
  live:
    permission: silverstone.owner
  localchat:
    aliases: [ lc, local ]
    permission: silverstone.admin
    usage: "§cUsage: /localchat <message>"
  monitortps:
    aliases: [ tpsmonitor ]
    permission: silverstone.admin
    usage: "Usage: /monitortps [interval]"
  nv:
    aliases: [ nightvision ]
    permission: silverstone.nightvision
  quickrestart:
    permission: silverstone.admin
  rank:
    description: "Check your ranks"
  restart:
    aliases: [ cancelrestart ]
    permission: silverstone.admin
  restartwhenempty:
    permission: silverstone.admin
  rules:
    description: "Shows the server's rules"
  safk:
    description: "Silently toggle AFK"
    permission: silverstone.moderator
  schedulerestart:
    permission: silverstone.admin
  shrug:
    description: "Shrug emote"
  silverstoneglobal:
    aliases: [ ssg ]
    permission: silverstone.admin
    usage: "Usage: /ssg reload"
  social:
    description: "Open the social GUI!"
  spectate:
    aliases: [ spec ]
    permission: silverstone.trialmod
    usage: "§cUsage: /spectate <player>"
  tableflip:
    description: "Tableflip emote"
  tpchunk:
    permission: silverstone.admin
    usage: "§cUsage: /tpchunk <x> <z> [world]"
  tpregion:
    permission: silverstone.admin
    usage: "§cUsage: /tpregion <x> <z> [world]"
  twitch:
    description: "A social command"
  twitter:
    description: "A social command"
  updatecommands:
    description: "Updates available commands"
  watch:
    permission: silverstone.trialmod
    usage: "§cUsage: /watch <player>"
  youtube:
    description: "A social command"

permissions:
  silverstone.admin:
    default: op
  silverstone.chatcolor:
    default: op
  silverstone.chatsounds.enabled:
    default: false
  silverstone.chatsounds:
    default: false
  silverstone.console:
    default: op
  silverstone.jlsounds.enabled:
    default: false
  silverstone.jlsounds:
    default: op
  silverstone.moderator:
    default: op
  silverstone.mvp:
    default: false
  silverstone.nightvision:
    default: op
  silverstone.owner:
    default: op
  silverstone.trialmod:
    default: op
  silverstone.vip+:
    default: false
  silverstone.exit:
    default: true
  silverstone.live:
    default: false
  silverstone.fixlight:
    default: true
