main: net.silverstonemc.silverstoneglobal.SilverstoneGlobal
name: SilverstoneGlobal
description: Designed for the Silverstone network backend servers
version: %VERSION%
author: JasonHorkles
api-version: '1.21.4'
softdepend:
  - DiscordSRV
  - Essentials
depend:
  - LuckPerms
loadbefore:
  - WorldGuardExtraFlags

commands:
  bclag:
    permission: silverstone.admin
  bcnolag:
    permission: silverstone.admin
  bcrestart:
    permission: silverstone.admin
  bcshutdown:
    permission: silverstone.admin
  buy:
    aliases: [ ranks, donate ]
  bwarn:
    description: "Send warning from backend server to proxy"
    permission: silverstone.owner
    usage: "§cUsage: /bwarn <player> <reason>"
  centeronblock:
    permission: silverstone.admin
  chatcolor:
    permission: silverstone.chatcolor
  discord:
    aliases: [ news ]
  effects:
    permission: silverstone.moderator
  exit:
    permission: silverstone.exit
  forcerestart:
    permission: silverstone.admin
  freezeserver:
    permission: silverstone.owner
    usage: "§cUsage: /freezeserver <seconds> confirm"
  ggamerule:
    permission: silverstone.admin
    usage: "§cUsage: /globalgamerule <gamerule> <value>"
  glist:
    description: "Workaround for proxy aliasing"
  help:
    description: "Shows help"
  listops:
    aliases: [ oplist ]
    permission: silverstone.admin
  live:
    permission: silverstone.owner
  localchat:
    aliases: [ lc, local ]
    permission: silverstone.admin
    usage: "§cUsage: /localchat <message>"
  monitortps:
    aliases: [ tpsmonitor ]
    permission: silverstone.admin
    usage: "Usage: /monitortps [interval]"
  nv:
    aliases: [ nightvision ]
    permission: silverstone.nightvision
  quickrestart:
    permission: silverstone.admin
  restart:
    aliases: [ cancelrestart ]
    permission: silverstone.admin
  restartwhenempty:
    permission: silverstone.admin
  schedulerestart:
    permission: silverstone.admin
  spectate:
    aliases: [ spec ]
    permission: silverstone.moderator
    usage: "§cUsage: /spectate <player>"
  ssgrl:
    permission: silverstone.admin
  stuck:
    aliases: [ trapped ]
    permission: silverstone.stuck
  tips:
    description: "Server tips"
  tpchunk:
    permission: silverstone.admin
    usage: "§cUsage: /tpchunk <x> <z> [world]"
  tpregion:
    permission: silverstone.admin
    usage: "§cUsage: /tpregion <x> <z> [world]"
  updatecommands:
    description: "Updates available commands"
  watch:
    permission: silverstone.moderator
    usage: "§cUsage: /watch <player>"

permissions:
  silverstone.admin:
    default: op
  silverstone.chatcolor:
    default: op
  silverstone.exit:
    default: true
  silverstone.live:
    default: false
  silverstone.moderator:
    default: op
  silverstone.nightvision:
    default: op
  silverstone.owner:
    default: op
  silverstone.stuck:
    default: false
