name: Bug Report
description: Report a bug with the server
labels: [ Bug-Unconfirmed ]
body:
  - type: markdown
    attributes:
      value: |
        Please keep your title relatively short, as more info will be requested below

  - type: dropdown
    attributes:
      label: World the issue occured in
      description: Your current world can be found in the player tab list
      options:
        - creative
        - flyingcourse
        - mini_golf
        - minigames
    validations:
      required: true

  - type: input
    attributes:
      label: Location
      description: Please provide either the coordinates or a notable location at/near the issue (if applicable)
      placeholder: "-3956, 72, 593 OR Death Run Nether"
    validations:
      required: false

  - type: input
    attributes:
      label: My Minecraft username
      placeholder: JasonHorkles
    validations:
      required: true

  - type: textarea
    attributes:
      label: What I was doing before/when the issue occurred
      placeholder: "I was the killer in the Death Run map and pushed the pressure plate"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened
      description: "What exactly was the issue?"
      placeholder: "The pressure plate broke but nothing happened"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What was supposed to happen
      placeholder: "Something should've happened after the pressure plate broke"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional details
      description: "Provide any additional details, if any, that should be noted (pictures/videos of it happening, etc)"
    validations:
      required: false
