name: Punishment Appeal
description: Use this if you were jailed, banned, or some other punishment and want it to be appealed
title: Punishment Appeal
labels: Appeal
body:
- type: input
  attributes:
    label: My Minecraft username
    placeholder: JasonHorkles
  validations:
    required: true

- type: input
  attributes:
    label: My current rank
    description: "Shown in the player tab list | If you're banned, use your last known rank"
    placeholder: default
  validations:
    required: true

- type: textarea
  attributes:
    label: What I did to get punished
  validations:
    required: true

- type: textarea
  attributes:
    label: Why I want my punishment to be lifted
  validations:
    required: true

- type: input
  attributes:
    label: "Will I ever repeat what I did to get punished?"
  validations:
    required: true

- type: checkboxes
  attributes:
    label: "By checking this box I agree to never again do what I did to get punished. I also understand that future appeals may not be accepted if I am punished again."
    options:
      - label: I agree
        required: false
