# https://minecraft.wiki/w/Protocol_version#Java_Edition_2
# Kick the player if protocol version is below this value
minimum-protocol-version: 763
minimum-version: '1.20'
# Send warning message to the player if protocol version is not this value
current-protocol-version: 767
current-version: '1.21'

rules:
  # The text to add before the rule number when sending a player a rule
  rule-prefix: "<dark_green>{#} <gray>| <bold>"
  header:
    - ""
    - "<dark_aqua> ---------- <green>Rules <dark_aqua>----------"
    - ""
  rules:
    1: "<dark_green>DO</bold> <#23B8CF>be kind and use common sense"
    2: "<dark_green>DO</bold> <#23B8CF>respect all players & staff"
    3: "<gold>PLEASE</bold> <#23B8CF>only speak English <dark_aqua>(use <gray><click:suggest_command:/tell >/tell <player></click> <dark_aqua>to speak another language)"
    4: "<gold>PLEASE</bold> <#23B8CF>avoid excessive swearing"
    5: "<red>DON'T</bold> <#23B8CF>spam"
    6: "<red>DON'T</bold> <#23B8CF>impersonate others"
    7: "<red>DON'T</bold> <#23B8CF>intentionally lag the server or abuse the Creative plots"
    8: "<red>NO</bold> <#23B8CF>NSFW content"
    9: "<red>NO</bold> <#23B8CF>advertising"
    10: "<red>NO</bold> <#23B8CF>hacked or unfairly modified clients"
    11: "<red>NO</bold> <#23B8CF>exploits / cheating"
    12: "<red>NO</bold> <#23B8CF>anti-AFK methods"
  footer:
    - ""
    - "<dark_aqua>Type <green><click:suggest_command:/tips>/tips</click> <dark_aqua>to get a list of all tips for the server!"

nicknames:
  # The prefix and suffix for all users with nicknames - leave blank for no prefix/suffix
  prefix: ''
  suffix: ''

  # The maximum length of a nickname
  max-length: 16

url-filter: "\\b(?:https?:\\/\\/)?(?!(?:github\\.com|(play|survival)?\\.?silverstonemc\\.net|twitch\\.tv\\/jasonhorkles)\\b)[a-zA-Z0-9-]+(?:\\.[a-zA-Z]{2,})+(?:\\/\\S*)?\\b"



########################################
#               Warnings               #
########################################

# Use placeholder {player} for the player's name
reasons:
  afk:
    description: "Using an anti-AFK machine or macro"
    add:
      1:
        - "kick {player} Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been kicked for <gray>using an anti-AFK machine / macro"
      2:
        - "ban {player} 30m Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been banned [30m] for <gray>using an anti-AFK machine / macro"
      3:
        - "ban {player} 1h Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been banned [1h] for <gray>using an anti-AFK machine / macro"
      4:
        - "ban {player} 6h Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been banned [6h] for <gray>using an anti-AFK machine / macro"
      5:
        - "ban {player} 12h Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been banned [12h] for <gray>using an anti-AFK machine / macro"
      6:
        - "ban {player} 1d Anti-AFK machine / macro [Rule 10]"
        - "bc <gray>{player} <red>has been banned [1d] for <gray>using an anti-AFK machine / macro"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  banevasion:
    description: "Evading a ban by using an alternate account"
    add:
      1:
        - "ban {player} Ban evasion"
        - "ipban {player} Ban evasion"
        - "bc <gray>{player} <red>has been banned for <gray>ban evasion"
    remove:
      1:
        - "unban {player}"
        - "unbanip {player}"

  chat:
    description: "Violating any rule regarding chat"
    add:
      1:
        - "mute {player} 15m Chat abuse [Rules 1 - 7 | 11 - Warning 1/7]"
        - "bc <gray>{player} <red>has been muted for <gray>15 minutes <dark_aqua>[Warning 1/7]"
      2:
        - "mute {player} 30m Chat abuse [Rules 1 - 7 | 11 - Warning 2/7]"
        - "bc <gray>{player} <red>has been muted for <gray>30 minutes <dark_aqua>[Warning 2/7]"
      3:
        - "mute {player} 1h Chat abuse [Rules 1 - 7 | 11 - Warning 3/7]"
        - "bc <gray>{player} <red>has been muted for <gray>1 hour <dark_aqua>[Warning 3/7]"
      4:
        - "mute {player} 1d Chat abuse [Rules 1 - 7 | 11 - Warning 4/7]"
        - "bc <gray>{player} <red>has been muted for <gray>1 day <dark_aqua>[Warning 4/7]"
      5:
        - "mute {player} 7d Chat abuse [Rules 1 - 7 | 11 - Warning 5/7]"
        - "bc <gray>{player} <red>has been muted for <gray>7 days <dark_aqua>[Warning 5/7]"
      6:
        - "mute {player} 1mo Chat abuse [Rules 1 - 7 | 11 - Warning 6/7]"
        - "bc <gray>{player} <red>has been muted for <gray>1 month <dark_aqua>[Warning 6/7]"
      7:
        - "mute {player} -1 Chat abuse [Rules 1 - 7 | 11 - Warning 7/7]"
        - "bc <gray>{player} <red>has been permanently muted <dark_aqua>[Warning 7/7]"
    remove:
      1:
        - "unmute {player}"
      2:
        - "unmute {player}"
      3:
        - "unmute {player}"
      4:
        - "unmute {player}"
      5:
        - "unmute {player}"
      6:
        - "unmute {player}"
      7:
        - "unmute {player}"

  exploits:
    description: "Using an exploit within Minecraft, the server, or simply finding ways to cheat"
    add:
      1:
        - "ban {player} 1d Exploits / cheating [Rule 9 - Warning 1/4]"
        - "bc <gray>{player} <red>has been banned [1d] for <gray>exploits / cheating <dark_aqua>[Warning 1/4]"
      2:
        - "ban {player} 7d Exploits / cheating [Rule 9 - Warning 2/4]"
        - "bc <gray>{player} <red>has been banned [7d] for <gray>exploits / cheating <dark_aqua>[Warning 2/4]"
      3:
        - "ban {player} 1mo Exploits / cheating [Rule 9 - Warning 3/4]"
        - "bc <gray>{player} <red>has been banned [1mo] for <gray>exploits / cheating <dark_aqua>[Warning 3/4]"
      4:
        - "ban {player} -1 Exploits / cheating [Rule 9 - Warning 4/4]"
        - "bc <gray>{player} <red>has been banned for <gray>exploits / cheating <dark_aqua>[Warning 4/4]"
    remove:
      1:
        - "unban {player}"
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"

  malicious-client:
    description: "(Mostly anti-cheat handled) Any hack or disallowed client activity"
    add:
      1:
        - "kick {player} Malicious client activity [Rule 8 - Warning 1/6]"
        - "bc <gray>{player} <red>has been kicked for <gray>malicious client activity <dark_aqua>[Warning 1/6]"
      2:
        - "ban {player} 1h Malicious client activity [Rule 8 - Warning 2/6]"
        - "bc <gray>{player} <red>has been banned [1h] for <gray>malicious client activity <dark_aqua>[Warning 2/6]"
      3:
        - "ban {player} 1d Malicious client activity [Rule 8 - Warning 3/6]"
        - "bc <gray>{player} <red>has been banned [1d] for <gray>malicious client activity <dark_aqua>[Warning 3/6]"
      4:
        - "ban {player} 7d Malicious client activity [Rule 8 - Warning 4/6]"
        - "bc <gray>{player} <red>has been banned [7d] for <gray>malicious client activity <dark_aqua>[Warning 4/6]"
      5:
        - "ban {player} 1mo Malicious client activity [Rule 8 - Warning 5/6]"
        - "bc <gray>{player} <red>has been banned [1mo] for <gray>malicious client activity <dark_aqua>[Warning 5/6]"
      6:
        - "ban {player} -1 Malicious client activity [Rule 8 - Warning 6/6]"
        - "bc <gray>{player} <red>has been banned for <gray>malicious client activity <dark_aqua>[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  nickname:
    description: "Abuse of nickname privelages, such as impersonation or any other rule violation (after verbal warning)"
    add:
      1:
        - "nick reset {player}"
        - "lpv user {player} parent addtemp nonick 7d"
        - "bc <gray>{player} <red>can no longer change their nickname for <gray>7 days <dark_aqua>[Warning 1/4]"
      2:
        - "nick reset {player}"
        - "lpv user {player} parent addtemp nonick 14d"
        - "bc <gray>{player} <red>can no longer change their nickname for <gray>14 days <dark_aqua>[Warning 2/4]"
      3:
        - "nick reset {player}"
        - "lpv user {player} parent addtemp nonick 1mo"
        - "bc <gray>{player} <red>can no longer change their nickname for <gray>1 month <dark_aqua>[Warning 3/4]"
      4:
        - "nick reset {player}"
        - "lpv user {player} parent add nonick"
        - "bc <gray>{player} <red>can no longer change their nickname <dark_aqua>[Warning 4/4]"
    remove:
      1:
        - "lpv user {player} parent removetemp nonick"
      2:
        - "lpv user {player} parent removetemp nonick"
      3:
        - "lpv user {player} parent removetemp nonick"
      4:
        - "lpv user {player} parent remove nonick"

  other:
    description: "Any rule violation that doesn't have its own dedicated warning (non-hacking)"
    add:
      1:
        - "kick {player} Violating rules - Ask a moderator for more info [Warning 1/7]"
        - "bc <gray>{player} <red>has been kicked for <gray>violating rules <dark_aqua>[Warning 1/7]"
      2:
        - "ban {player} 6h Violating rules [Warning 2/7]"
        - "bc <gray>{player} <red>has been banned [6h] for <gray>violating rules <dark_aqua>[Warning 2/7]"
      3:
        - "ban {player} 12h Violating rules [Warning 3/7]"
        - "bc <gray>{player} <red>has been banned [12h] for <gray>violating rules <dark_aqua>[Warning 3/7]"
      4:
        - "ban {player} 1d Violating rules [Warning 4/7]"
        - "bc <gray>{player} <red>has been banned [1d] for <gray>violating rules <dark_aqua>[Warning 4/7]"
      5:
        - "ban {player} 7d Violating rules [Warning 5/7]"
        - "bc <gray>{player} <red>has been banned [7d] for <gray>violating rules <dark_aqua>[Warning 5/7]"
      6:
        - "ban {player} 1mo Violating rules [Warning 6/7]"
        - "bc <gray>{player} <red>has been banned [1mo] for <gray>violating rules <dark_aqua>[Warning 6/7]"
      7:
        - "ban {player} -1 Violating rules [Warning 7/7]"
        - "bc <gray>{player} <red>has been banned for <gray>violating rules <dark_aqua>[Warning 7/7]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"
      7:
        - "unban {player}"

  admin:
    description: "(Anti-cheat handled) When an admin permission is detected"
    add:
      1:
        - "ban {player} -1 Illegal permission detected"
        - "ipban {player} -1 Illegal permission detected"
        - "bc <gray>{player} <red>has been banned for <gray>having illegal permissions"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an admin permission! :warning:"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an admin permission! :warning:"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an admin permission! :warning:"
    remove:
      1:
        - "unban {player}"

  plot-abuse:
    description: "Attempting to make the server lag via machines, entities, etc, or any other means of abusing creative plots"
    add:
      1:
        - "lpv user {player} permission settemp plots.permpack.basic false 7d"
        - "bc <gray>{player} <red>has been temporarily banned from using the Creative plots [7d] due to <gray>plot abuse <dark_aqua>[Warning 1/3]"
      2:
        - "lpv user {player} permission settemp plots.permpack.basic false 1mo"
        - "bc <gray>{player} <red>has been temporarily banned from using the Creative plots [1mo] due to <gray>plot abuse <dark_aqua>[Warning 2/3]"
      3:
        - "lpv user {player} permission set plots.permpack.basic false"
        - "bc <gray>{player} <red>has been banned from using the Creative plots due to <gray>plot abuse <dark_aqua>[Warning 3/3]"
    remove:
      1:
        - "lpv user {player} permission unsettemp plots.permpack.basic"
      2:
        - "lpv user {player} permission unsettemp plots.permpack.basic"
      3:
        - "lpv user {player} permission unset plots.permpack.basic"

  skin:
    description: "If a player's skin is inappropriate or offensive"
    add:
      1:
        - "kick {player} Inappropriate skin - please change it before re-joining [Rule 1 - Warning 1/6]"
        - "bc <gray>{player} <red>has been kicked for <gray>using an inappropriate skin <dark_aqua>[Warning 1/6]"
      2:
        - "ban {player} 7d Inappropriate skin [Rule 1 - Warning 2/6]"
        - "bc <gray>{player} <red>has been banned [7d] for <gray>using an inappropriate skin <dark_aqua>[Warning 2/6]"
      3:
        - "ban {player} 14d Inappropriate skin [Rule 1 - Warning 3/6]"
        - "bc <gray>{player} <red>has been banned [14d] for <gray>using an inappropriate skin <dark_aqua>[Warning 3/6]"
      4:
        - "ban {player} 30d Inappropriate skin [Rule 1 - Warning 4/6]"
        - "bc <gray>{player} <red>has been banned [30d] for <gray>using an inappropriate skin <dark_aqua>[Warning 4/6]"
      5:
        - "ban {player} 60d Inappropriate skin [Rule 1 - Warning 5/6]"
        - "bc <gray>{player} <red>has been banned [60d] for <gray>using an inappropriate skin <dark_aqua>[Warning 5/6]"
      6:
        - "ban {player} -1 Inappropriate skin [Rule 1 - Warning 6/6]"
        - "bc <gray>{player} <red>has been banned for <gray>using an inappropriate skin <dark_aqua>[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"
