# https://wiki.vg/Protocol_version_numbers
# Kick the player if protocol version is below this value
minimum-protocol-version: 759 #1.19
# Send warning message to the player if protocol version is below this value
current-protocol-version: 762
current-version: 1.19.4

rules:
  # The text to add before the rule number when sending a player a rule
  rule-prefix: "<dark_green>{#} <gray>| <#23B8CF>"
  header:
    - ""
    - "<dark_aqua> ---------- <green>Rules <dark_aqua>----------"
    - ""
  rules:
    1: "No NSFW content"
    2: "Don't spam"
    3: "Be kind and use common sense"
    4: "No advertising"
    5: "Respect all players & staff"
    6: "Only speak English <dark_aqua>(use <gray><click:suggest_command:/tell >/tell <player></click> <dark_aqua>to speak another language)"
    7: "Don't excessively swear"
    8: "No hacked or heavily modified clients"
    9: "No exploits / cheating"
    10: "No anti-AFK methods"
    11: "Don't impersonate others"
    12: "Don't intentionally lag the server or abuse the Creative plots"
  footer:
    - ""
    - "<dark_aqua>Type <green>/tips <dark_aqua>to get a list of all tips for the server!"
