rules:
  # The text to add before the rule number when sending a player a rule
  rule-prefix: "<dark_green>{#} <gray>| <#23B8CF>"
  header:
    - ""
    - "<dark_aqua> ---------- <green>Rules <dark_aqua>----------"
    - ""
  rules:
    1: "No swearing and don't try to bypass the swear filter"
    2: "Hacked clients and <#15E8E8><click:open_url:https://github.com/SilverstoneMC/Silverstone/wiki/Modifications><underlined>some modifications</underlined>*</click> <#23B8CF>are prohibited"
    3: "No griefing / exploits / cheating <dark_aqua>(includes x-ray resource packs)"
    4: "Don't spam <dark_aqua>(neither caps nor characters)"
    5: "Be kind and use common sense"
    6: "No anti-AFK methods"
    7: "No advertising"
    8: "Respect all players & staff"
    9: "Only talk in English <dark_aqua>(use <gray><click:suggest_command:/tell >/tell <player></click> <dark_aqua>to speak another language)"
    10: "Don't impersonate others"
    11: "Don't build within 200 blocks of someone else without their permission"
  footer:
    - ""
    - "<dark_aqua>Type <green>/tips <dark_aqua>to get a list of all tips for the server!"
