minigame-world: minigames
flying-course-world: flying_course

random-game:
  singleplayer:
    - Parkour
    - Mazes
    - Mini Golf
    - Flying Course
  multiplayer:
    - Mini Golf
    - Spleef
    - Hide & Seek
    - Boat Racing
    - Death Run
    - PvP
    - TNT Run