empty-minigame-world: mini_empty
terrain-minigame-world: mini_terrain
amplified-minigame-world: mini_amplified

random-game:
  singleplayer:
    - Parkour
    - Mazes
    - Mini Golf
    - Flying Course
  multiplayer:
    - Mini Golf
    - Spleef
    - Hide & Seek
    - Boat Racing
    - Death Run
    - PvP
    - TNT Run