empty-minigame-world: mini_empty
terrain-minigame-world: mini_terrain
amplified-minigame-world: mini_amplified

fc-speed-boost-multiplier: 1.075

random-game:
  singleplayer:
    - Game1
  multiplayer:
    - Game2