main: net.silverstonemc.silverstoneminigames.SilverstoneMinigames
name: SilverstoneMinigames
description: Designed for the Minigames server
version: %VERSION%
author: JasonHorkles
api-version: '1.21.8'

commands:
  doublejump:
    permission: silverstone.owner
    usage: "§cUsage: /doublejump <player> <count | reset>"
  flyingcourse:
    description: "Reset the player if they touch an illegal block"
    permission: silverstone.owner
    usage: "/flyingcourse <player>"
  hideseek:
    permission: silverstone.owner
    usage: "/hideseek <<assign_block | heartbeat | random_taunt> [players] | reset_taunt_points>"
  htp:
    aliases: [ howtoplay ]
    description: "GUI for how to play the minigames"
  minigame:
    aliases: [ game, whatminigameshouldiplay ]
    description: "Choose a random minigame"
  ssmrl:
    description: "Reload the plugin"
    permission: silverstone.admin
  tntrun:
    permission: silverstone.owner
    usage: "/tntrun <player>"
  fcfinish:
    description: "Ran when the flying course is completed"
    permission: silverstone.owner
#  miniholo:
#    permission: silverstone.admin
#    usage: "/miniholo <hologram> <open | ready | in_session | resetting | closed>"
  corruptedtag:
    permission: silverstone.owner
    usage: "/corruptedtag <start | stop | kitselect | corrupt | uncorrupt> <players>"
  clearbossbars:
    permission: silverstone.owner
    usage: "/clearbossbars <player>"
  minigamemanager:
    aliases: [ mgm ]
    permission: silverstone.admin

permissions:
  silverstone.minigames.flyingcourse:
    default: false
    description: Allow using `/zfinish` command
  silverstone.minigames.hideseek.taunt.bypasscooldown:
    default: false
  silverstone.minigames.hideseek.taunt:
    default: false
  silverstone.minigames.pvp:
    default: false
    description: Will heal players with this perm on kill
