main: me.jasonhorkles.randomteleportlimit.RandomTeleportLimit
name: RandomTeleportLimit
version: %VERSION%
author: JasonHorkles
api-version: 1.17
depend:
  - RandomTeleport

commands:
  rtplimit:
    description: "Base command for the RTP Limit plugin"
    usage: "§cUsage: /rtplimit <reload | check [player]>"
    permission: rtplimit.command

permissions:
  rtplimit.command:
    default: op
  rtplimit.reload:
    default: op
  rtplimit.check:
    default: op
  rtplimit.limit.admin:
    description: Bypass the RTP limit
    default: op
  rtplimit.limit.mvp:
    default: false
  rtplimit.limit.vip+:
    default: false
  rtplimit.limit.vip:
    default: false
  rtplimit.limit.member:
    default: false