main: net.silverstonemc.silverstonemain.SilverstoneMain
name: SilverstoneMain
description: Designed for whatever the main server is at the time
version: %VERSION%
author: JasonHorkles
api-version: 1.19
softdepend:
  - DiscordSRV
  - Essentials

commands:
  gettingstarted:
    description: "Get started message"
  homec:
    permission: silverstone.owner
  ssm:
    permission: silverstone.admin
    usage: "§cUsage: /ssm reload"

permissions:
  silverstone.joinleavespam.bypass:
    default: op
