main: net.silverstonemc.silverstonemain.SilverstoneMain
name: SilverstoneMain
description: Designed for the Main server
version: %VERSION%
author: JasonHorkles
api-version: 1.18
softdepend:
  - DiscordSRV
  - LuckPerms
  - Multiverse-Core
  - PremiumVanish
  - RandomTeleport

commands:
  allowend:
    description: "Allows the player to enter The End"
  dragon:
    aliases: [ enderdragon ]
  enablecollision:
    description: "Enable collision"
  gettingstarted:
    description: "Get started message"
  homec:
    permission: silverstone.owner
  homes?:
    description: "Show how many homes the player can set"
  keepinv:
    description: "Toggle keepInventory"
  regenend:
    description: "Regenerate The End"
  relay:
    permission: silverstone.console
  rtplimit:
    description: "Check a player's RTP usages"
    permission: silverstone.trialmod
    usage: "§cUsage: /rtplimit check <player>"
  ssm:
    permission: silverstone.admin
    usage: "§cUsage: /ssm reload"
  stopmusic:
    description: "Stop the currently playing music"
  togglemusic:
    aliases: [ disablemusic, enablemusic ]
    description: "Toggle auto music"
  znewbiekit:
    permission: silverstone.console
    usage: "/znewbiekit <player>"
#    remove
  togglesellstickconfirmation:
    description: "Enable/disable the Sell Stick confirmation"

permissions:
  silverstone.joinleavespam.bypass:
    default: op
  silverstone.rtplimit.bypass:
    default: op
    description: Bypass the RTP limit
  silverstone.rtplimit.member:
    default: false
  silverstone.rtplimit.mvp:
    default: false
  silverstone.rtplimit.vip+:
    default: false
  silverstone.rtplimit.vip:
    default: false
