main: net.silverstonemc.silverstonemain.SilverstoneMain
name: SilverstoneMain
description: Designed for whatever the main server is at the time
version: %VERSION%
author: JasonHorkles
api-version: '1.21.1'
softdepend:
  - Essentials

commands:
  gettingstarted:
    description: "Get started message"
  homec:
    permission: silverstone.owner
