main: net.silverstonemc.silverstonemain.SilverstoneMain
name: SilverstoneMain
description: Designed for the Main server
version: %VERSION%
author: JasonHorkles
api-version: 1.18
softdepend:
  - Essentials
  - DiscordSRV
  - Multiverse-Core
  - ProtectionStones
  - RandomTeleport
  - Vault

commands:
  allowend:
    description: "Allows the player to enter The End"
  claimpoints:
    aliases: [ redeemclaimpoints ]
    usage: "§cUsage: /claimpoints view [player]\n§cModerator usage: /claimpoints <give|take> <player> <amount>"
  dragon:
    aliases: [ enderdragon ]
  enablecollision:
    description: "Enable collision"
  gettingstarted:
    description: "Get started message"
  hideitemframe:
    permission: silverstone.hideitemframe
  homec:
    permission: silverstone.owner
  homes?:
    description: "Show how many homes the player can set"
  keepinv:
    description: "Toggle keepInventory"
  masshideitemframes:
    permission: silverstone.hideitemframe
  regenend:
    description: "Regenerate The End"
    permission: silverstone.owner
  relay:
    permission: silverstone.console
  rtplimit:
    description: "Check a player's RTP usages"
    permission: silverstone.trialmod
    usage: "§cUsage: /rtplimit check <player>"
  ssm:
    permission: silverstone.admin
    usage: "§cUsage: /ssm reload"
  znewbiekit:
    permission: silverstone.console
    usage: "/znewbiekit <player>"

permissions:
  expensivedeaths.bypass:
    default: false
  silverstone.hideitemframe:
    default: op
  silverstone.joinleavespam.bypass:
    default: op
  silverstone.rtplimit.bypass:
    default: op
    description: Bypass the RTP limit
  silverstone.rtplimit.member:
    default: false
  silverstone.rtplimit.mvp:
    default: false
  silverstone.rtplimit.vip+:
    default: false
  silverstone.rtplimit.vip:
    default: false
