main: net.silverstonemc.silverstonemain.SilverstoneMain
name: SilverstoneMain
description: Designed for whatever the main server is at the time
version: %VERSION%
author: JasonHorkles
api-version: '1.20'
softdepend:
  - DiscordSRV
  - Essentials

commands:
  gettingstarted:
    description: "Get started message"
  homec:
    permission: silverstone.owner
  velocitytest:
    permission: silverstone.console
    usage: "/velocitytest <player> <x> <y> <z>"
