# Use placeholder {player} for the player's name
reasons:
  afk:
    description: "Using an anti-AFK machine or macro"
    add:
      1:
        - "kick {player} Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been kicked for &busing an anti-AFK machine / macro"
      2:
        - "tempban {player} 30m Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been tempbanned [30m] for &busing an anti-AFK machine / macro"
      3:
        - "tempban {player} 1h Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been tempbanned [1h] for &busing an anti-AFK machine / macro"
      4:
        - "tempban {player} 6h Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been tempbanned [6h] for &busing an anti-AFK machine / macro"
      5:
        - "tempban {player} 12h Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been tempbanned [12h] for &busing an anti-AFK machine / macro"
      6:
        - "tempban {player} 1d Anti-AFK machine / macro [Rule 10]"
        - "bc &b{player} &ahas been tempbanned [1d] for &busing an anti-AFK machine / macro"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  banevasion:
    description: "Evading a ban by using an alternate account"
    add:
      1:
        - "ban {player} Ban evasion"
        - "banip {player} Ban evasion"
        - "bc &b{player} &ahas been banned for &bban evasion"
    remove:
      1:
        - "unban {player}"

  chat:
    description: "Violating any rule regarding chat"
    add:
      1:
        - "tempmute {player} 15m Chat abuse [Rules 1 - 7 | 11 - Warning 1/7]"
        - "bc &b{player} &ahas been muted for &b15 minutes &3[Warning 1/7]"
      2:
        - "tempmute {player} 30m Chat abuse [Rules 1 - 7 | 11 - Warning 2/7]"
        - "bc &b{player} &ahas been muted for &b30 minutes &3[Warning 2/7]"
      3:
        - "tempmute {player} 1h Chat abuse [Rules 1 - 7 | 11 - Warning 3/7]"
        - "bc &b{player} &ahas been muted for &b1 hour &3[Warning 3/7]"
      4:
        - "tempmute {player} 1d Chat abuse [Rules 1 - 7 | 11 - Warning 4/7]"
        - "bc &b{player} &ahas been muted for &b1 day &3[Warning 4/7]"
      5:
        - "tempmute {player} 7d Chat abuse [Rules 1 - 7 | 11 - Warning 5/7]"
        - "bc &b{player} &ahas been muted for &b7 days &3[Warning 5/7]"
      6:
        - "tempmute {player} 1mo Chat abuse [Rules 1 - 7 | 11 - Warning 6/7]"
        - "bc &b{player} &ahas been muted for &b1 month &3[Warning 6/7]"
      7:
        - "mute {player} Chat abuse [Rules 1 - 7 | 11 - Warning 7/7]"
        - "bc &b{player} &ahas been permanently muted &3[Warning 7/7]"
    remove:
      1:
        - "unmute {player}"
      2:
        - "unmute {player}"
      3:
        - "unmute {player}"
      4:
        - "unmute {player}"
      5:
        - "unmute {player}"
      6:
        - "unmute {player}"
      7:
        - "unmute {player}"

  exploits:
    description: "Using an exploit within Minecraft / the server or simply finding ways to cheat"
    add:
      1:
        - "tempban {player} 1d Exploits / cheating [Rule 9 - Warning 1/4]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bexploits / cheating &3[Warning 1/4]"
      2:
        - "tempban {player} 7d Exploits / cheating [Rule 9 - Warning 2/4]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bexploits / cheating &3[Warning 2/4]"
      3:
        - "tempban {player} 1mo Exploits / cheating [Rule 9 - Warning 3/4]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bexploits / cheating &3[Warning 3/4]"
      4:
        - "ban {player} Exploits / cheating [Rule 9 - Warning 4/4]"
        - "bc &b{player} &ahas been banned for &bexploits / cheating &3[Warning 4/4]"
    remove:
      1:
        - "unban {player}"
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"

  hitbox:
    description: "(Anti-cheat handled) Hitbox or Reach hack is used"
    add:
      1:
        - "kick {player} Hitbox / Reach hack [Rule 8 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &bHitbox / Reach hack &3[Warning 1/6]"
      2:
        - "tempban {player} 6h Hitbox / Reach hack [Rule 8 - Warning 2/6]"
        - "bc &b{player} &ahas been tempbanned [6h] for &bHitbox / Reach hack &3[Warning 2/6]"
      3:
        - "tempban {player} 1d Hitbox / Reach hack [Rule 8 - Warning 3/6]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bHitbox / Reach hack &3[Warning 3/6]"
      4:
        - "tempban {player} 7d Hitbox / Reach hack [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bHitbox / Reach hack &3[Warning 4/6]"
      5:
        - "tempban {player} 1mo Hitbox / Reach hack [Rule 8 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bHitbox / Reach hack &3[Warning 5/6]"
      6:
        - "ban {player} Hitbox / Reach hack [Rule 8 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &bHitbox / Reach hack &3[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  interact:
    description: "(Anti-cheat handled) Interacting with blocks or entities in non-vanilla ways"
    add:
      1:
        - "kick {player} Illegal interactions with blocks/entities [Rule 8 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &bIllegal interactions with blocks/entities &3[Warning 1/6]"
      2:
        - "tempban {player} 6h Illegal interactions with blocks/entities [Rule 8 - Warning 2/6]"
        - "bc &b{player} &ahas been tempbanned [6h] for &bIllegal interactions with blocks/entities &3[Warning 2/6]"
      3:
        - "tempban {player} 7d Illegal interactions with blocks/entities [Rule 8 - Warning 3/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bIllegal interactions with blocks/entities &3[Warning 3/6]"
      4:
        - "tempban {player} 7d Illegal interactions with blocks/entities [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bIllegal interactions with blocks/entities &3[Warning 4/6]"
      5:
        - "tempban {player} 1mo Illegal interactions with blocks/entities [Rule 8 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bIllegal interactions with blocks/entities &3[Warning 5/6]"
      6:
        - "ban {player} Illegal interactions with blocks/entities [Rule 8 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &bIllegal interactions with blocks/entities &3[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  join-leave-spam:
    description: "(Anti-cheat handled) Repeatedly joining and leaving the server to create join / leave message spam"
    add:
      1:
        - "tempban {player} 30s Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [30s] for &bjoin / leave spam"
      2:
        - "tempban {player} 1m Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [1m] for &bjoin / leave spam"
      3:
        - "tempban {player} 10m Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [10m] for &bjoin / leave spam"
      4:
        - "tempban {player} 30m Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [30m] for &bjoin / leave spam"
      5:
        - "tempban {player} 1h Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [1h] for &bjoin / leave spam"
      6:
        - "tempban {player} 1d Join / Leave spam"
        - "bc &b{player} &ahas been tempbanned [1d] for &bjoin / leave spam"
    remove:
      1:
        - "unban {player}"
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  killaura:
    description: "(Anti-cheat handled) Automatic hitting and/or aiming"
    add:
      1:
        - "kick {player} KillAura hack or related [Rule 8 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &bKillAura hack or related &3[Warning 1/6]"
      2:
        - "tempban {player} 6h KillAura hack or related [Rule 8 - Warning 2/6]"
        - "bc &b{player} &ahas been tempbanned [6h] for &bKillAura hack or related &3[Warning 2/6]"
      3:
        - "tempban {player} 1d KillAura hack or related [Rule 8 - Warning 3/6]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bKillAura hack or related &3[Warning 3/6]"
      4:
        - "tempban {player} 7d KillAura hack or related [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bKillAura hack or related &3[Warning 4/6]"
      5:
        - "tempban {player} 1mo KillAura hack or related [Rule 8 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bKillAura hack or related &3[Warning 5/6]"
      6:
        - "ban {player} KillAura hack or related [Rule 8 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &bKillAura hack or related &3[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  malicious-client:
    description: "(Partially anti-cheat handled) Any unlisted hack or disallowed client activity"
    add:
      1:
        - "kick {player} Malicious client activity [Rule 8 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &bmalicious client activity &3[Warning 1/6]"
      2:
        - "tempban {player} 1h Malicious client activity [Rule 8 - Warning 2/6]"
        - "bc &b{player} &ahas been tempbanned [1h] for &bmalicious client activity &3[Warning 2/6]"
      3:
        - "tempban {player} 1d Malicious client activity [Rule 8 - Warning 3/6]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bmalicious client activity &3[Warning 3/6]"
      4:
        - "tempban {player} 7d Malicious client activity [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bmalicious client activity &3[Warning 4/6]"
      5:
        - "tempban {player} 1mo Malicious client activity [Rule 8 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bmalicious client activity &3[Warning 5/6]"
      6:
        - "ban {player} Malicious client activity [Rule 8 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &bmalicious client activity &3[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  move:
    description: "(Anti-cheat handled) Speed, Fly, or other hack related to abnormal movement"
    add:
      1:
        - "kick {player} Speed / Fly / abnormal movement hack [Rule 8 - Warning 1/5]"
        - "bc &b{player} &ahas been kicked for &bSpeed / Fly / abnormal movement hack &3[Warning 1/5]"
      2:
        - "tempban {player} 1d Speed / Fly / abnormal movement hack [Rule 8 - Warning 2/5]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bSpeed / Fly / abnormal movement hack &3[Warning 2/5]"
      3:
        - "tempban {player} 7d Speed / Fly / abnormal movement hack [Rule 8 - Warning 3/5]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bSpeed / Fly / abnormal movement hack &3[Warning 3/5]"
      4:
        - "tempban {player} 1mo Speed / Fly / abnormal movement hack [Rule 8 - Warning 4/5]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bSpeed / Fly / abnormal movement hack &3[Warning 4/5]"
      5:
        - "ban {player} Speed / Fly / abnormal movement hack [Rule 8 - Warning 5/5]"
        - "bc &b{player} &ahas been banned for &bSpeed / Fly / abnormal movement hack &3[Warning 5/5]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"

  nickname:
    description: "Abuse of nickname privelages, such as impersonation or any other rule violation (after verbal warning)"
    add:
      1:
        - "resetname {player}"
        - "lpb user {player} parent addtemp nonick 7d"
        - "bc &b{player} &acan no longer change their nickname for &b7 days &3[Warning 1/4]"
      2:
        - "resetname {player}"
        - "lpb user {player} parent addtemp nonick 14d"
        - "bc &b{player} &acan no longer change their nickname for &b14 days &3[Warning 2/4]"
      3:
        - "resetname {player}"
        - "lpb user {player} parent addtemp nonick 1mo"
        - "bc &b{player} &acan no longer change their nickname for &b1 month &3[Warning 3/4]"
      4:
        - "resetname {player}"
        - "lpb user {player} parent add nonick"
        - "bc &b{player} &acan no longer change their nickname &3[Warning 4/4]"
    remove:
      1:
        - "lpb user {player} parent removetemp nonick"
      2:
        - "lpb user {player} parent removetemp nonick"
      3:
        - "lpb user {player} parent removetemp nonick"
      4:
        - "lpb user {player} parent remove nonick"

  other:
    description: "Any rule violation that doesn't have its own dedicated warning (non-hacking)"
    add:
      1:
        - "kick {player} Violating rules - Ask a moderator for more info [Warning 1/7]"
        - "bc &b{player} &ahas been kicked for &bviolating rules &3[Warning 1/7]"
      2:
        - "tempban {player} 6h Violating rules [Warning 2/7]"
        - "bc &b{player} &ahas been tempbanned [6h] for &bviolating rules &3[Warning 2/7]"
      3:
        - "tempban {player} 12h Violating rules [Warning 3/7]"
        - "bc &b{player} &ahas been tempbanned [12h] for &bviolating rules &3[Warning 3/7]"
      4:
        - "tempban {player} 1d Violating rules [Warning 4/7]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bviolating rules &3[Warning 4/7]"
      5:
        - "tempban {player} 7d Violating rules [Warning 5/7]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bviolating rules &3[Warning 5/7]"
      6:
        - "tempban {player} 1mo Violating rules [Warning 6/7]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bviolating rules &3[Warning 6/7]"
      7:
        - "ban {player} Violating rules [Warning 7/7]"
        - "bc &b{player} &ahas been banned for &bviolating rules &3[Warning 7/7]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"
      7:
        - "unban {player}"

  owner:
    description: "(Anti-cheat handled) When an owner permission is detected"
    add:
      1:
        - "ban {player} Illegal permission detected"
        - "banip {player} Illegal permission detected"
        - "bc &b{player} &ahas been banned for &bhaving illegal permissions"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an owner permission! :warning:"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an owner permission! :warning:"
        - "relay staff :warning: <@&667793980318154783>, player `{player}` was auto banned for having an owner permission! :warning:"
    remove:
      1:
        - "unban {player}"

  plot-abuse:
    description: "Attempting to make the server lag via machines, entities, etc, or any other means of abusing creative plots"
    add:
      1:
        - "lpb user {player} permission settemp plots.permpack.basic false 1d"
        - "bc &b{player} &ahas been temporarily banned from using the Creative plots [1d] due to &bplot abuse &3[Warning 1/4]"
      2:
        - "lpb user {player} permission settemp plots.permpack.basic false 7d"
        - "bc &b{player} &ahas been temporarily banned from using the Creative plots [1d] due to &bplot abuse &3[Warning 2/4]"
      3:
        - "lpb user {player} permission settemp plots.permpack.basic false 1mo"
        - "bc &b{player} &ahas been temporarily banned from using the Creative plots [1d] due to &bplot abuse &3[Warning 3/4]"
      4:
        - "lpb user {player} permission set plots.permpack.basic false"
        - "bc &b{player} &ahas been banned from using the Creative plots due to &bplot abuse &3[Warning 4/4]"
    remove:
      1:
        - "unban {player}"
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"

  skin:
    description: "If a player's skin is inappropriate or offensive"
    add:
      1:
        - "kick {player} Inappropriate skin - please change it before re-joining [Rule 1 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &busing an inappropriate skin &3[Warning 1/6]"
      2:
        - "tempban {player} 7d Inappropriate skin [Rule 1 - Warning 2/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &busing an inappropriate skin &3[Warning 2/6]"
      3:
        - "tempban {player} 14d Inappropriate skin [Rule 1 - Warning 3/6]"
        - "bc &b{player} &ahas been tempbanned [14d] for &busing an inappropriate skin &3[Warning 3/6]"
      4:
        - "tempban {player} 30d Inappropriate skin [Rule 1 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [30d] for &busing an inappropriate skin &3[Warning 4/6]"
      5:
        - "tempban {player} 60d Inappropriate skin [Rule 1 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [60d] for &busing an inappropriate skin &3[Warning 5/6]"
      6:
        - "ban {player} Inappropriate skin [Rule 1 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &busing an inappropriate skin &3[Warning 6/6]"
    remove:
      1: [ ]
      2:
        - "unban {player}"
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"

  velocity:
    description: "(Anti-cheat handled) Using anti-knockback cheats to attack players and entities easier"
    add:
      1:
        - "kick {player} Velocity / Anti-Knockback hack [Rule 8 - Warning 1/6]"
        - "bc &b{player} &ahas been kicked for &bVelocity / Anti-Knockback hack &3[Warning 1/6]"
      2:
        - "kick {player} Velocity / Anti-Knockback hack [Rule 8 - Warning 2/6]"
        - "bc &b{player} &ahas been kicked for &bVelocity / Anti-Knockback hack &3[Warning 2/6]"
      3:
        - "tempban {player} 1d Velocity / Anti-Knockback hack [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [1d] for &bVelocity / Anti-Knockback hack &3[Warning 4/6]"
      4:
        - "tempban {player} 7d Velocity / Anti-Knockback hack [Rule 8 - Warning 4/6]"
        - "bc &b{player} &ahas been tempbanned [7d] for &bVelocity / Anti-Knockback hack &3[Warning 4/6]"
      5:
        - "tempban {player} 1mo Velocity / Anti-Knockback hack [Rule 8 - Warning 5/6]"
        - "bc &b{player} &ahas been tempbanned [1mo] for &bVelocity / Anti-Knockback hack &3[Warning 5/6]"
      6:
        - "ban {player} Velocity / Anti-Knockback hack [Rule 8 - Warning 6/6]"
        - "bc &b{player} &ahas been banned for &bVelocity / Anti-Knockback hack &3[Warning 6/6]"
    remove:
      1: [ ]
      2: [ ]
      3:
        - "unban {player}"
      4:
        - "unban {player}"
      5:
        - "unban {player}"
      6:
        - "unban {player}"
