main: me.jasonhorkles.silverstonewarnings.SilverstoneWarnings
name: SilverstoneWarnings
description: The warning system for Silverstone
version: %VERSION%
author: JasonHorkles
api-version: 1.17
softdepend:
  - DiscordSRV

commands:
  warn:
    description: "Warn a player"
    usage: "§cUsage: §7/warn <player> [category]"
    permission: sswarnings.warn
  warnings:
    description: "Check a player's warnings"
    usage: "§cPlease specify a player!"
  warnqueue:
    description: "View all the warnings in the queue."
    permission: sswarnings.warn
  silverstonewarnings:
    aliases: [ ssw ]
    description: "Base command for the plugin"
    usage: "§cUsage: §7/ssw §8<§7remove <reason> <player> [-s] §8|§7 clear <[reason]|all> <player> [-s] §8|§7 reload§8>"
    permission: sswarnings.command
  reasons:
    description: "Show the available warning reasons"
    permission: sswarnings.command
  warnlist:
    description: "Show a list of all given warnings"
    permission: sswarnings.warn

permissions:
  sswarnings.warn:
    description: Allow warning players
    default: op
  sswarnings.command:
    description: Access to various commands
    default: op
  sswarnings.admin:
    description: Admin commands
    default: op